version: 2

updates:
  - package-ecosystem: npm
    directory: /
    schedule:
      interval: weekly
      day: monday
      time: '09:00'
      timezone: Europe/London
    open-pull-requests-limit: 5
    versioning-strategy: increase-if-necessary
    groups:
      routine-production:
        dependency-type: production
        update-types:
          - minor
          - patch
      routine-development:
        dependency-type: development
        update-types:
          - minor
          - patch
    ignore:
      - dependency-name: '*'
        update-types:
          - version-update:semver-major
    commit-message:
      prefix: deps
      include: scope

  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: weekly
      day: monday
      time: '09:30'
      timezone: Europe/London
    open-pull-requests-limit: 3
    groups:
      github-actions:
        patterns:
          - '*'
    commit-message:
      prefix: ci
      include: scope
