export const SimulationConfig = {
  SIMULATION_HZ: 120,
  get DT() {
    return 1 / this.SIMULATION_HZ;
  },

  PITCH_LENGTH: 105,
  PITCH_WIDTH: 68,
  get PITCH_HALF_LENGTH() {
    return this.PITCH_LENGTH / 2;
  },
  get PITCH_HALF_WIDTH() {
    return this.PITCH_WIDTH / 2;
  },
  GOAL_WIDTH: 7.32,
  GOAL_HEIGHT: 2.44,
  get GOAL_HALF_WIDTH() {
    return this.GOAL_WIDTH / 2;
  },

  MATCH_DURATION_SECONDS: 90,
  GOAL_CELEBRATION_SECONDS: 3.0,
  KICKOFF_DELAY_SECONDS: 2.0,
  HALFTIME_SECONDS: 3.0,

  BALL_RADIUS: 0.11,
  BALL_MASS: 0.43,
  BALL_FRICTION: 0.965,
  BALL_GRAVITY: 9.81,
  BALL_BOUNCINESS: 0.62,
  BALL_BOUNCE_DEAD_ZONE: 0.4,
  BALL_AIR_DRAG: 0.994,

  PLAYER_MAX_SPEED: 6.5,
  PLAYER_SPRINT_SPEED: 8.5,
  PLAYER_ACCEL: 18.0,
  PLAYER_DECEL: 28.0,
  PLAYER_TURN_SPEED_WALK: 14.0,
  PLAYER_TURN_SPEED_SPRINT: 5.0,
  get PLAYER_TURN_SPEED() {
    return this.PLAYER_TURN_SPEED_WALK;
  },
  PLAYER_CONTROL_RADIUS: 0.8,

  TACKLE_RANGE: 1.4,
  TACKLE_DURATION: 0.35,
  TACKLE_COOLDOWN: 1.2,
  SLIDE_RANGE: 2.0,
  SLIDE_DURATION: 0.5,
  SLIDE_COOLDOWN: 1.8,

  TOUCH_IDEAL_DIST: 0.4,
  TOUCH_FORCE_MAX: 10.0,
  TOUCH_CADENCE_MAX_INTERVAL: 0.40,
  TOUCH_CADENCE_MIN_INTERVAL: 0.10,
  TOUCH_TETHER_GAIN: 4.0,

  PASS_POWER_BASE: 7.0,
  SHOT_POWER_BASE: 13.0,
  MAX_CHARGE_TIME: 1.2,
  MIN_CHARGE_FRACTION: 0.2,

  KEEPER_MAX_SPEED: 6.0,
  KEEPER_RUSH_SPEED: 8.5,
  KEEPER_DIVE_SPEED: 10.0,
  KEEPER_LOOKAHEAD_TIME: 0.4,
  KEEPER_PREDICT_MAX_TIME: 1.5,
  KEEPER_SAVE_RADIUS: 2.0,
  KEEPER_DIVE_TRIGGER_RADIUS: 4.5,
  KEEPER_DIVE_MIN_BALL_SPEED: 3.5,
  KEEPER_DIVE_DURATION: 0.55,
  KEEPER_RECOVER_DURATION: 0.75,
  KEEPER_RECOVER_SPEED_MULT: 0.85,
  KEEPER_RECOVER_RETURN_RATE: 8,
  KEEPER_BOX_DEPTH: 16.5,
  KEEPER_BOX_HALF_WIDTH: 20.15,
  KEEPER_THROUGH_BALL_MIN_VY: 3.0,
  KEEPER_THROUGH_BALL_MIN_SPEED: 4.0,
  KEEPER_LOOSE_BALL_MAX_SPEED: 3.0,
  KEEPER_PASSBACK_WINDOW: 3.0, CONTAIN_SPEED_MULT: 0.58, CONTAIN_TURN_MULT: 1.35,
  FAKE_SHOT_MAX_CHARGE: 0.18, FAKE_SHOT_BURST_MULT: 2.2, THROUGH_LEAD_BASE: 3.0, THROUGH_LEAD_CHARGE_SCALE: 4.5,

  // Dead ball restarts
  GOAL_KICK_DELAY: 1.5,
  THROW_IN_DELAY: 1.0,
  THROW_IN_MAX_POWER: 5.0,
  CORNER_KICK_DELAY: 2.0,
  FREE_KICK_DELAY: 2.0,
  FREE_KICK_WALL_DIST: 9.15,
  SIX_YARD_BOX_DEPTH: 5.5,
  CORNER_ARC_OFFSET: 0.5,

  // Keeper expansion
  KEEPER_CATCH_MAX_SPEED: 8.0,
  KEEPER_HOLD_DURATION: 3.0,
  KEEPER_THROW_POWER: 8.0,
  KEEPER_PUNT_POWER: 14.0,
  KEEPER_PUNT_LIFT: 8.0,
  KEEPER_THROW_LIFT: 1.0,
  KEEPER_1V1_RUSH_DIST: 20.0,
  KEEPER_SPREAD_DIST: 5.0,
  KEEPER_SPREAD_RADIUS_MULT: 1.4,

  // Timed finishing
  TIMED_FINISH_WINDOW_START: 0.60,
  TIMED_FINISH_WINDOW_END: 0.75,
  TIMED_FINISH_POWER_BOOST: 1.15,
  TIMED_FINISH_ERROR_MULT: 0.5,

  // Volley / half-volley
  VOLLEY_MIN_Z: 0.3,
  VOLLEY_MAX_Z: 1.2,
  VOLLEY_POWER_MULT: 1.25,
  VOLLEY_ERROR_MULT: 1.4,
  HALF_VOLLEY_POWER_MULT: 1.1,
  HALF_VOLLEY_ERROR_MULT: 0.8,

  // Weak foot / shot error
  WEAK_FOOT_ERROR_MULT: 1.4,

  // Foul system
  FOUL_BEHIND_DOT_THRESHOLD: -0.3,
  FOUL_LATE_TACKLE_WINDOW: 0.3,
  FOUL_EXCESSIVE_SPEED_MULT: 1.3,
  FOUL_COOLDOWN: 2.0,

  // Pass intelligence
  PASS_FRICTION_FACTOR: 2.8,
  PASS_LEAD_FACTOR: 0.6,
  SHORT_PASS_ANGLE_DOT: 0.5,
};
