export const SimulationConfig = {
  SIMULATION_HZ: 120,
  get DT() {
    return 1 / this.SIMULATION_HZ;
  },

  PITCH_LENGTH: 105,
  PITCH_WIDTH: 68,
  get PITCH_HALF_LENGTH() {
    return this.PITCH_LENGTH / 2;
  },
  get PITCH_HALF_WIDTH() {
    return this.PITCH_WIDTH / 2;
  },
  GOAL_WIDTH: 7.32,
  GOAL_HEIGHT: 2.44,
  get GOAL_HALF_WIDTH() {
    return this.GOAL_WIDTH / 2;
  },

  MATCH_DURATION_SECONDS: 90,
  GOAL_CELEBRATION_SECONDS: 3.0,
  KICKOFF_DELAY_SECONDS: 2.0,

  BALL_RADIUS: 0.11,
  BALL_MASS: 0.43,
  BALL_FRICTION: 0.965,
  BALL_GRAVITY: 9.81,
  BALL_BOUNCINESS: 0.62,
  BALL_BOUNCE_DEAD_ZONE: 0.4,
  BALL_AIR_DRAG: 0.994,

  PLAYER_MAX_SPEED: 6.5,
  PLAYER_SPRINT_SPEED: 8.5,
  PLAYER_ACCEL: 18.0,
  PLAYER_DECEL: 28.0,
  PLAYER_TURN_SPEED_WALK: 14.0,
  PLAYER_TURN_SPEED_SPRINT: 5.0,
  get PLAYER_TURN_SPEED() {
    return this.PLAYER_TURN_SPEED_WALK;
  },
  PLAYER_CONTROL_RADIUS: 0.8,

  TOUCH_IDEAL_DIST: 0.4,
  TOUCH_FORCE_MAX: 10.0,
  TOUCH_CADENCE_MAX_INTERVAL: 0.40,
  TOUCH_CADENCE_MIN_INTERVAL: 0.10,
  TOUCH_TETHER_GAIN: 4.0,

  PASS_POWER_BASE: 7.0,
  SHOT_POWER_BASE: 13.0,
  MAX_CHARGE_TIME: 1.2,
  MIN_CHARGE_FRACTION: 0.2,

  KEEPER_MAX_SPEED: 6.0,
  KEEPER_DIVE_SPEED: 10.0,
  KEEPER_LOOKAHEAD_TIME: 0.4,
  KEEPER_SAVE_RADIUS: 2.0,
  KEEPER_DIVE_TRIGGER_RADIUS: 4.5,
  KEEPER_DIVE_MIN_BALL_SPEED: 3.5,
  KEEPER_DIVE_DURATION: 0.55,
  KEEPER_RECOVER_DURATION: 1.2,
};
