export type CommentaryCategory =
  | 'goal_home' | 'goal_away' | 'shot_home' | 'shot_away' | 'near_miss_home' | 'near_miss_away'
  | 'tackle_home' | 'tackle_away' | 'offside_home' | 'offside_away' | 'kickoff' | 'halftime'
  | 'full_time' | 'full_time_win_home' | 'full_time_win_away' | 'full_time_draw' | 'buildup_home' | 'buildup_away';

export interface CommentaryTemplate { id: string; category: CommentaryCategory; text: string; }
const ADJECTIVES = ['crisp','clever','dangerous','incisive','patient','relentless','sharp','swift','tenacious','thunderous'];
export function pickAdjective(rng: () => number): string { return ADJECTIVES[Math.floor(rng() * ADJECTIVES.length)]!; }
export const COMMENTARY_TEMPLATES: CommentaryTemplate[] = [
  { id: 'gh-1', category: 'goal_home', text: 'GOAL! {playerTeam} find the net! {score} at {minute} minutes!' },
  { id: 'gh-2', category: 'goal_home', text: 'What a finish! {playerTeam} score! It is {score} after {minute} minutes.' },
  { id: 'gh-3', category: 'goal_home', text: 'They have done it! {playerTeam} break through! {score} at {minute}.' },
  { id: 'gh-4', category: 'goal_home', text: 'Back of the net! {playerTeam} lead the charge! {score}, {minute} minutes gone.' },
  { id: 'gh-5', category: 'goal_home', text: 'Sensational! {playerTeam} score! {score} at {minute}.' },
  { id: 'gh-6', category: 'goal_home', text: 'Clinical from {playerTeam}! {score}, {minute} minutes played.' },
  { id: 'gh-7', category: 'goal_home', text: 'Unstoppable! {playerTeam} find a way through! {score} at {minute}.' },
  { id: 'gh-8', category: 'goal_home', text: 'Get in! {playerTeam} have scored! {score} with {minute} on the clock.' },
  { id: 'ga-1', category: 'goal_away', text: 'Goal for {playerTeam}! {score} at {minute} minutes.' },
  { id: 'ga-2', category: 'goal_away', text: '{playerTeam} strike! It is {score} after {minute} minutes.' },
  { id: 'ga-3', category: 'goal_away', text: 'They have scored! {playerTeam} make it {score} at {minute}.' },
  { id: 'ga-4', category: 'goal_away', text: 'Brilliant from {playerTeam}! {score}, {minute} minutes.' },
  { id: 'ga-5', category: 'goal_away', text: '{playerTeam} punish the defence! {score} at {minute}.' },
  { id: 'ga-6', category: 'goal_away', text: 'What a moment! {playerTeam} score! {score}, minute {minute}.' },
  { id: 'ga-7', category: 'goal_away', text: 'Against the run of play, {playerTeam} score! {score} at {minute}.' },
  { id: 'ga-8', category: 'goal_away', text: '{playerTeam} find the corner! {score} after {minute} minutes.' },
  { id: 'sh-1', category: 'shot_home', text: '{playerTeam} unleash a {adj} shot!' },
  { id: 'sh-2', category: 'shot_home', text: 'Effort on goal from {playerTeam}!' },
  { id: 'sh-3', category: 'shot_home', text: '{playerTeam} try their luck from range!' },
  { id: 'sh-4', category: 'shot_home', text: 'Shot! {playerTeam} test the keeper at {minute} minutes.' },
  { id: 'sh-5', category: 'shot_home', text: '{playerTeam} with a {adj} strike toward goal!' },
  { id: 'sh-6', category: 'shot_home', text: 'Here comes a shot from {playerTeam}!' },
  { id: 'sh-7', category: 'shot_home', text: '{playerTeam} let fly! {score} on the scoreboard.' },
  { id: 'sa-1', category: 'shot_away', text: '{playerTeam} with a {adj} effort on goal!' },
  { id: 'sa-2', category: 'shot_away', text: 'Shot from {playerTeam}! The keeper is tested.' },
  { id: 'sa-3', category: 'shot_away', text: '{playerTeam} try to bend one in!' },
  { id: 'sa-4', category: 'shot_away', text: 'Dangerous shot from {playerTeam} at {minute} minutes.' },
  { id: 'sa-5', category: 'shot_away', text: '{playerTeam} with a {adj} attempt!' },
  { id: 'sa-6', category: 'shot_away', text: 'Effort on goal! {playerTeam} push forward.' },
  { id: 'nmh-1', category: 'near_miss_home', text: 'So close for {playerTeam}! Just wide!' },
  { id: 'nmh-2', category: 'near_miss_home', text: '{playerTeam} almost score! Inches away!' },
  { id: 'nmh-3', category: 'near_miss_home', text: 'Off the post! {playerTeam} so nearly score!' },
  { id: 'nmh-4', category: 'near_miss_home', text: 'What a chance for {playerTeam}! Cleared off the line!' },
  { id: 'nma-1', category: 'near_miss_away', text: '{playerTeam} nearly score! Just past the post!' },
  { id: 'nma-2', category: 'near_miss_away', text: 'So close from {playerTeam}! The crowd gasps!' },
  { id: 'nma-3', category: 'near_miss_away', text: '{playerTeam} almost find the net! Keeper breathes a sigh of relief.' },
  { id: 'th-1', category: 'tackle_home', text: '{playerTeam} win the ball with a {adj} tackle!' },
  { id: 'th-2', category: 'tackle_home', text: 'Brilliant defending from {playerTeam}!' },
  { id: 'th-3', category: 'tackle_home', text: '{playerTeam} dispossess their opponent cleanly.' },
  { id: 'th-4', category: 'tackle_home', text: 'Tackle won! {playerTeam} regain possession.' },
  { id: 'th-5', category: 'tackle_home', text: '{playerTeam} with a {adj} challenge to win it back!' },
  { id: 'ta-1', category: 'tackle_away', text: '{playerTeam} steal the ball with authority!' },
  { id: 'ta-2', category: 'tackle_away', text: 'Tackle won by {playerTeam}!' },
  { id: 'ta-3', category: 'tackle_away', text: '{playerTeam} with a {adj} interception.' },
  { id: 'ta-4', category: 'tackle_away', text: 'Strong challenge from {playerTeam}!' },
  { id: 'oh-1', category: 'offside_home', text: 'Flag up! {playerTeam} caught offside at {minute} minutes.' },
  { id: 'oh-2', category: 'offside_home', text: 'Offside against {playerTeam}. Play stopped.' },
  { id: 'oh-3', category: 'offside_home', text: 'Linesman raises the flag. {playerTeam} offside.' },
  { id: 'oa-1', category: 'offside_away', text: 'Offside! {playerTeam} are penalised at {minute}.' },
  { id: 'oa-2', category: 'offside_away', text: 'The flag is up against {playerTeam}.' },
  { id: 'oa-3', category: 'offside_away', text: 'Offside given. {playerTeam} were just ahead of the line.' },
  { id: 'ko-1', category: 'kickoff', text: 'And we are underway! {score} as the match kicks off.' },
  { id: 'ko-2', category: 'kickoff', text: 'The referee blows the whistle. Play begins!' },
  { id: 'ko-3', category: 'kickoff', text: 'Here we go! The ball is rolling.' },
  { id: 'ko-4', category: 'kickoff', text: 'Kick off! Both sides looking to impose themselves early.' },
  { id: 'ko-5', category: 'kickoff', text: 'Underway at {minute} minutes. {score} on the board.' },
  { id: 'ht-1', category: 'halftime', text: 'Half time! The score is {score} after {minute} minutes.' },
  { id: 'ht-2', category: 'halftime', text: 'The whistle blows for half time. {score} at the break.' },
  { id: 'ht-3', category: 'halftime', text: 'Forty-five minutes gone. Half time, and it is {score}.' },
  { id: 'ht-4', category: 'halftime', text: 'Interval. {score} after an entertaining first half.' },
  { id: 'ht-5', category: 'halftime', text: 'Half time whistle. {score}. Both teams head to the dressing room.' },
  { id: 'ft-1', category: 'full_time', text: 'Full time! The final score is {score}.' },
  { id: 'ft-2', category: 'full_time', text: 'There goes the final whistle! {score} at full time.' },
  { id: 'ft-3', category: 'full_time', text: 'That is it! Ninety minutes played. {score}.' },
  { id: 'ftw-h-1', category: 'full_time_win_home', text: 'Full time! The home side win {score}! What a performance!' },
  { id: 'ftw-h-2', category: 'full_time_win_home', text: 'Victory for the home team! {score} at the final whistle.' },
  { id: 'ftw-a-1', category: 'full_time_win_away', text: 'Full time! The away side take it {score}!' },
  { id: 'ftw-a-2', category: 'full_time_win_away', text: 'Away win! {score} as the referee blows for full time.' },
  { id: 'ftd-1', category: 'full_time_draw', text: 'Full time! It ends all square at {score}.' },
  { id: 'ftd-2', category: 'full_time_draw', text: 'Honours even! {score} at the final whistle.' },
  { id: 'bu-h-1', category: 'buildup_home', text: '{playerTeam} keeping possession at {minute} minutes. {score}.' },
  { id: 'bu-h-2', category: 'buildup_home', text: '{playerTeam} probing forward with {adj} passing.' },
  { id: 'bu-h-3', category: 'buildup_home', text: 'Patient build-up from {playerTeam}. {score} on the clock.' },
  { id: 'bu-h-4', category: 'buildup_home', text: '{playerTeam} looking to create something here.' },
  { id: 'bu-h-5', category: 'buildup_home', text: '{minute} minutes played. {playerTeam} in control. {score}.' },
  { id: 'bu-a-1', category: 'buildup_away', text: '{playerTeam} dictating the tempo at {minute} minutes.' },
  { id: 'bu-a-2', category: 'buildup_away', text: '{playerTeam} with a {adj} spell of possession.' },
  { id: 'bu-a-3', category: 'buildup_away', text: '{playerTeam} working the ball well. {score}.' },
  { id: 'bu-a-4', category: 'buildup_away', text: 'Good movement from {playerTeam} in midfield.' },
  { id: 'bu-a-5', category: 'buildup_away', text: '{minute} minutes on the clock. {playerTeam} on the front foot.' },
];
export const TEMPLATES_BY_CATEGORY = COMMENTARY_TEMPLATES.reduce((acc, t) => {
  (acc[t.category] ??= []).push(t);
  return acc;
}, {} as Record<CommentaryCategory, CommentaryTemplate[]>);
